# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

# KEY STEP: Use HashMap.

import collections
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        hm = collections.defaultdict(int)
        for w in s:
            hm[w] += 1
        for w in t:
            if w not in hm:
                return w
            else:
                hm[w] -= 1
        for key in hm:
            if hm[key] < 0:
                return key